# Generated by Django 5.0.1 on 2024-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Bandworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bandworks_details', models.CharField(max_length=50)),
                ('Bandworks_files', models.FileField(upload_to='workDoc/')),
            ],
        ),
    ]
