# Generated by Django 5.0.1 on 2024-03-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicBand', '0003_tbl_bandworks_musicaltype_tbl_bandworks_musicband'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bandgallery',
            name='bandwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicBand.tbl_bandworks'),
        ),
    ]
