# Generated by Django 5.0.1 on 2024-02-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_musicaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_place',
            name='dist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district'),
        ),
    ]
