# Generated by Django 5.0.1 on 2024-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_musicbandverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_AcceptedMusicband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accepted_Musicband', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_RejectedMusicband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rejected_Musicband', models.CharField(max_length=100)),
            ],
        ),
    ]
