# Generated by Django 5.0.1 on 2024-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_acceptedmusicband_tbl_rejectedmusicband'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_AcceptedFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accepted_Freelancer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_FreelancerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freelancer_Verification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_RejectedFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rejected_Freelancer', models.CharField(max_length=100)),
            ],
        ),
    ]
