# Generated by Django 5.0.1 on 2024-02-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_acceptedfreelancer_tbl_freelancerverification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_AcceptedFreelancer',
        ),
        migrations.DeleteModel(
            name='tbl_AcceptedMusicband',
        ),
        migrations.DeleteModel(
            name='tbl_FreelancerVerification',
        ),
        migrations.DeleteModel(
            name='tbl_MusicbandVerification',
        ),
        migrations.DeleteModel(
            name='tbl_RejectedFreelancer',
        ),
        migrations.DeleteModel(
            name='tbl_RejectedMusicband',
        ),
    ]
