# Generated by Django 5.0.1 on 2024-02-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_acceptedfreelancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='dist',
            new_name='district',
        ),
    ]
