# Generated by Django 5.0.1 on 2024-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_details', models.CharField(max_length=50)),
                ('Course_duration', models.CharField(max_length=50)),
                ('Course_amount', models.CharField(max_length=50)),
                ('Course_files', models.FileField(upload_to='courseDoc/')),
            ],
        ),
    ]
