# Generated by Django 5.0.1 on 2024-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_caption', models.CharField(max_length=50)),
                ('Gallery_files', models.FileField(upload_to='GllryDoc/')),
            ],
        ),
    ]
