# Generated by Django 5.0.1 on 2024-02-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_MusicalBandRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicalBandRegistration_name', models.CharField(max_length=50)),
            ],
        ),
    ]
