# Generated by Django 5.0.1 on 2024-02-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_logo',
            field=models.FileField(null=True, upload_to='BandDoc/'),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_proof',
            field=models.FileField(null=True, upload_to='BandDoc/'),
        ),
        migrations.AlterField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
