# Generated by Django 5.0.1 on 2024-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_musicalbandregistration_musicalbandregistration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_FreelancerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FreelancerRegistration_name', models.CharField(max_length=50, null=True)),
                ('FreelancerRegistration_contact', models.CharField(max_length=50, null=True)),
                ('FreelancerRegistration_email', models.CharField(max_length=50, null=True)),
                ('FreelancerRegistration_address', models.CharField(max_length=50, null=True)),
                ('FreelancerRegistration_place', models.CharField(max_length=50, null=True)),
                ('FreelancerRegistration_photo', models.FileField(null=True, upload_to='FreeDoc/')),
                ('FreelancerRegistration_proof', models.FileField(null=True, upload_to='FreeDoc/')),
                ('FreelancerRegistration_password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserRegistration_name', models.CharField(max_length=50, null=True)),
                ('UserRegistration_contact', models.CharField(max_length=50, null=True)),
                ('UserRegistration_email', models.CharField(max_length=50, null=True)),
                ('UserRegistration_address', models.CharField(max_length=50, null=True)),
                ('UserRegistration_place', models.CharField(max_length=50, null=True)),
                ('UserRegistration_photo', models.FileField(null=True, upload_to='UserDoc/')),
                ('UserRegistration_proof', models.FileField(null=True, upload_to='UserDoc/')),
                ('UserRegistration_password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
