# Generated by Django 5.0.1 on 2024-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_vstatus',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
