# Generated by Django 5.0.1 on 2024-02-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_dist_tbl_place_district'),
        ('Guest', '0007_alter_tbl_musicalbandregistration_musicalbandregistration_vstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_musicalbandregistration',
            name='MusicalBandRegistration_place',
        ),
        migrations.AddField(
            model_name='tbl_musicalbandregistration',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
