# Generated by Django 5.0.1 on 2024-02-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_dist_tbl_place_district'),
        ('Guest', '0008_remove_tbl_musicalbandregistration_musicalbandregistration_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_freelancerregistration',
            name='FreelancerRegistration_place',
        ),
        migrations.AddField(
            model_name='tbl_freelancerregistration',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
        migrations.AlterField(
            model_name='tbl_freelancerregistration',
            name='FreelancerRegistration_vstatus',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
