# Generated by Django 5.0.1 on 2024-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_remove_tbl_freelancerregistration_freelancerregistration_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_freelancerregistration',
            name='FreelancerRegistration_vstatus',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
