# Generated by Django 5.0.1 on 2024-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_SendComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendComplaint_title', models.CharField(max_length=50)),
                ('SendComplaint_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_SendFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendFeedback_feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
