# Generated by Django 5.0.1 on 2024-03-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_sendcomplaint_tbl_sendfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Bandbooking',
        ),
    ]
