# Generated by Django 5.0.1 on 2024-03-19 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_admin'),
        ('Guest', '0011_delete_tbl_userregistration'),
        ('MusicBand', '0004_tbl_bandgallery_bandwork'),
        ('User', '0003_delete_tbl_bandbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bandbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_venue', models.CharField(max_length=50)),
                ('booking_fordate', models.DateField()),
                ('booking_fortime', models.TimeField()),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.CharField(default=0, max_length=10)),
                ('booking_amount', models.CharField(default=0, max_length=50)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('bandwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicBand.tbl_bandworks')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
